### ISSUE TITLE
Lemons

### ISSUE THREAD

**Issue by QuantumFox42** [KingWaffleIII/Nuker-Bot#2]
I need it to create a channel, called "lemons", and spam at least 20 lemon pictures.

**Comment by QuantumFox42** [comment]
maybe add some settings for an on off button

**Comment by KingWaffleIII** [comment]
Hello @QuantumFox42,
Thank you for getting back to us! This is certainly an interesting request and you may see this being tested in the **development branch**. This has been marked as **low priority** since this isn't exactly a very useful request but I will get to it!

- KingWaffleIII

**Comment by KingWaffleIII** [comment]
Also, would you mind elaborating a little? What purpose would this serve? The second idea about the settings is certainly a good idea and you will likely see this in the next development pre-release version!

=> KingWaffleIII, project owner and administrator

**Comment by QuantumFox42** [comment]
high + low priority?

**Comment by KingWaffleIII** [comment]
There's two different requests here and the first one is low priority and the second is high priority. The settings request is very interesting and adds a level of customisability which is quite useful for the end user to control certain features. Whereas the first request about the lemon channel would be a good idea if this kind of thing was customisable (e.g. instead of lemons, it could be an orange channel) but it is a low priority request since I have more pressing matters.

**Comment by QuantumFox42** [comment]
👍

**Comment by KingWaffleIII** [comment]
Hello,
the latest commit at the time of writing on the dev branch addresses this request so I'm closing this issue now. You can expect to see this merge with the main branch soon :)
